/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.echo.clientserver.sayhello.client;

import com.echo.clientserver.sayhello.SayHello;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
/**
 *
 * @author FAUZI RAHMAT
 */
public class FormClient extends javax.swing.JFrame {
    private SayHello sayHello;
    /**
     * Creates new form FormClient
     */
    public FormClient() {
        try {
            sayHello = (SayHello) Naming.lookup("rmi://localhost:1099/sayHello");
        } catch (NotBoundException ex) {
            System.out.println("Terjadi Error Dengan Pesan : " + ex.getMessage());
            System.exit(1);
        } catch (MalformedURLException ex) {
            System.out.println("Terjadi Error Dengan Pesan : " + ex.getMessage());
            System.exit(1);
        } catch (RemoteException ex) {
            System.out.println("Terjadi Error Dengan Pesan : " + ex.getMessage());
            System.exit(1);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNama = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        lebelResponServer = new javax.swing.JLabel();
        textResponsServer = new javax.swing.JTextField();
        buttonSayHello = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));

        labelNama.setText("Nama :");

        lebelResponServer.setText("Respon Dari Server :");

        textResponsServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textResponsServerActionPerformed(evt);
            }
        });

        buttonSayHello.setText("Say Hello");
        buttonSayHello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSayHelloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lebelResponServer)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSayHello))
                    .addComponent(labelNama)
                    .addComponent(textResponsServer))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(labelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSayHello))
                .addGap(29, 29, 29)
                .addComponent(lebelResponServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textResponsServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textResponsServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textResponsServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textResponsServerActionPerformed

    private void buttonSayHelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSayHelloActionPerformed
        // TODO add your handling code here:
        try {
            String nama = textNama.getText();
            String response = sayHello.sayHello(nama);
            textResponsServer.setText(response);
        } catch (RemoteException ex) {
            System.err.println("Terjadi Error Dengan Pesan : " + ex.getMessage());
            System.exit(1);
        }
    }//GEN-LAST:event_buttonSayHelloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSayHello;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel lebelResponServer;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textResponsServer;
    // End of variables declaration//GEN-END:variables
}
